name: three_dart_jsm
description: three.js example/jsm rewrite by Dart. for three_dart Dart 3D library. an easy to use, lightweight, cross-platform, general purpose 3D library. 
version: 0.0.9
homepage: https://github.com/wasabia/three_dart_jsm

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  three_dart:
    git:
      url: https://github.com/Knightro63/three_dart.git
  flutter_gl: ^0.0.21
  typr_dart: ^0.0.2
  opentype_dart: ^0.0.1
  universal_html: ^2.0.8
  image: ^4.0.02
  archive: ^3.3.0

dependency_overrides:
#   flutter_gl:
#     path: ../../flutter_gl/flutter_gl
  three_dart:
    path: ../../three_dart


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
